[package]
name = "rust-url-shortener"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
lazy_static = "1.4"